const seedRequests=[{id:'REQ-2026-001',type:'Certificate of Indigency',date:'September 14, 2026',status:'Pending',purpose:'Medical assistance',owner:'resident'},{id:'REQ-2026-002',type:'Barangay Certificate',date:'September 08, 2026',status:'In process',purpose:'Job application',owner:'resident'},{id:'REQ-2026-003',type:'Barangay Certificate',date:'August 22, 2026',status:'Completed',purpose:'School requirement',owner:'resident'}];
const seedUpdates=[{id:1,type:'PROJECT UPDATE',title:'Road improvement project sa Purok 3',details:'Umabot na sa 75% ang konstruksyon. Inaasahang matatapos sa September 30, 2026.',date:'September 12, 2026'},{id:2,type:'ANNOUNCEMENT',title:'Barangay Assembly Meeting',details:'Inaanyayahan ang lahat sa quarterly assembly meeting sa covered court.',date:'September 20, 2026'}];
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const defaultAccounts=[{name:'Barangay Admin',email:'admin@barangay.ph',password:'admin123',role:'admin'}];let accounts=JSON.parse(localStorage.getItem('bc_accounts')||'null')||defaultAccounts;let currentUser=JSON.parse(localStorage.getItem('bc_user')||'null');let requests=JSON.parse(localStorage.getItem('bc_requests')||'null')||seedRequests;let updates=JSON.parse(localStorage.getItem('bc_updates')||'null')||seedUpdates;
function save(){localStorage.setItem('bc_accounts',JSON.stringify(accounts));localStorage.setItem('bc_requests',JSON.stringify(requests));localStorage.setItem('bc_updates',JSON.stringify(updates))}function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2700)}
function openPortal(user){if(user.role==='admin'){localStorage.setItem('bc_user',JSON.stringify(user));location.href='admin.html';return}currentUser=user;localStorage.setItem('bc_user',JSON.stringify(user));showApp();toast('Matagumpay na naka-login!')}
function showApp(){if(!currentUser||currentUser.role==='admin')return;$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userName').textContent=currentUser.name;$('#welcomeName').textContent=currentUser.name.split(' ')[0];renderRequests();renderUpdates();updateStats()}
function renderRequests(){const q=($('#searchRequests')?.value||'').toLowerCase(),f=$('#statusFilter')?.value||'all';const data=requests.filter(r=>(!r.owner||r.owner===currentUser.email||r.owner==='resident')&&(f==='all'||r.status===f)&&(`${r.type} ${r.id} ${r.purpose}`.toLowerCase().includes(q)));$('#requestsList').innerHTML=data.length?data.map(r=>`<article class="request-item"><div><h3>${r.type}</h3><small>${r.id} • ${r.date} • ${r.purpose}</small></div><span class="status ${r.status.toLowerCase().replace(' ','-')}">${r.status}</span></article>`).join(''):'<div class="request-item"><div><h3>Walang nahanap na request</h3><small>Mag-submit ng bagong request para makita dito.</small></div></div>'}
function renderUpdates(){const list=$('#communityUpdates');if(!list)return;list.innerHTML=updates.map((u,i)=>`<article class="update-card ${i===0?'featured':''}"><span class="tag">${u.type}</span><h2>${u.title}</h2><p>${u.details}</p><small>📅 ${u.date}</small></article>`).join('')}
function updateStats(){const own=requests.filter(r=>!r.owner||r.owner===currentUser.email||r.owner==='resident');$('#pendingCount').textContent=own.filter(r=>r.status==='Pending').length;$('#processCount').textContent=own.filter(r=>r.status==='In process').length;$('#completedCount').textContent=own.filter(r=>r.status==='Completed').length}
$$('.auth-tab').forEach(t=>t.addEventListener('click',()=>{$$('.auth-tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#loginForm').classList.toggle('hidden',t.dataset.auth!=='login');$('#signupForm').classList.toggle('hidden',t.dataset.auth!=='signup')}));
$('#loginBtn').addEventListener('click',()=>{const email=$('#loginEmail').value.trim().toLowerCase(),password=$('#loginPassword').value;const user=accounts.find(a=>a.email===email&&a.password===password);if(user)openPortal(user);else toast('Maling email o password.')});
$('#signupBtn').addEventListener('click',()=>{const role=$('#signupRole').value,name=$('#signupName').value.trim(),email=$('#signupEmail').value.trim().toLowerCase(),password=$('#signupPassword').value,password2=$('#signupPassword2').value;if(!name||!email||password.length<6||password!==password2||!$('#terms').checked)return toast('Punan nang tama ang lahat ng fields.');if(accounts.some(a=>a.email===email))return toast('May account na gamit ang email na ito. Mag-login na lang.');const user={name,email,password,role};accounts.push(user);save();openPortal(user)});
function goPage(page){$$('.page').forEach(p=>p.classList.add('hidden'));$(`#${page}Page`).classList.remove('hidden');$$('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.page===page));$('#mainNav').classList.remove('open')};$$('[data-page]').forEach(e=>e.addEventListener('click',()=>goPage(e.dataset.page)));
$$('[data-modal]').forEach(e=>e.addEventListener('click',()=>$('#requestModal').classList.remove('hidden')));$$('.modal-close').forEach(e=>e.addEventListener('click',()=>e.closest('.modal').classList.add('hidden')));$$('.service-card').forEach(e=>e.addEventListener('click',()=>{$('#documentType').value=e.dataset.request;$('#requestModal').classList.remove('hidden')}));$('#requestForm').addEventListener('submit',e=>{e.preventDefault();requests.unshift({id:`REQ-2026-${String(requests.length+1).padStart(3,'0')}`,type:$('#documentType').value,date:new Date().toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'}),status:'Pending',purpose:$('#requestReason').value,owner:currentUser.email});save();renderRequests();updateStats();$('#requestModal').classList.add('hidden');e.target.reset();goPage('requests');toast('Na-submit na ang iyong request!')});
$('#searchRequests').addEventListener('input',renderRequests);$('#statusFilter').addEventListener('change',renderRequests);$('.close-notice').addEventListener('click',e=>e.target.closest('.notice').remove());$('#mobileMenu').addEventListener('click',()=>$('#mainNav').classList.toggle('open'));$('#logoutBtn').addEventListener('click',()=>{localStorage.removeItem('bc_user');location.reload()});$('#settingsBtn').addEventListener('click',()=>$('#settingsModal').classList.remove('hidden'));$('#passwordForm').addEventListener('submit',e=>{e.preventDefault();const a=accounts.find(x=>x.email===currentUser.email);if(!a||a.password!==$('#currentPassword').value)return toast('Mali ang current password.');if($('#newPassword').value.length<6||$('#newPassword').value!==$('#newPassword2').value)return toast('Hindi tugma o kulang ang bagong password.');a.password=$('#newPassword').value;save();$('#settingsModal').classList.add('hidden');e.target.reset();toast('Na-update na ang password.')});$$('.toggle-password').forEach(b=>b.addEventListener('click',()=>{const i=b.previousElementSibling;i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'Show':'Hide'}));if(currentUser?.role==='admin')location.href='admin.html';else if(currentUser)showApp();
