const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const seedRequests=[{id:'REQ-2026-001',type:'Certificate of Indigency',date:'September 14, 2026',status:'Pending',purpose:'Medical assistance',owner:'resident'},{id:'REQ-2026-002',type:'Barangay Certificate',date:'September 08, 2026',status:'In process',purpose:'Job application',owner:'resident'},{id:'REQ-2026-003',type:'Barangay Certificate',date:'August 22, 2026',status:'Completed',purpose:'School requirement',owner:'resident'}];
const seedUpdates=[{id:1,type:'PROJECT UPDATE',title:'Road improvement project sa Purok 3',details:'Umabot na sa 75% ang konstruksyon. Inaasahang matatapos sa September 30, 2026.',date:'September 12, 2026'},{id:2,type:'ANNOUNCEMENT',title:'Barangay Assembly Meeting',details:'Inaanyayahan ang lahat sa quarterly assembly meeting sa covered court.',date:'September 20, 2026'}];
let accounts=JSON.parse(localStorage.getItem('bc_accounts')||'null')||[{name:'Barangay Admin',email:'admin@barangay.ph',password:'admin123',role:'admin'}];let currentUser=JSON.parse(localStorage.getItem('bc_user')||'null');let requests=JSON.parse(localStorage.getItem('bc_requests')||'null')||seedRequests;let updates=JSON.parse(localStorage.getItem('bc_updates')||'null')||seedUpdates;
const save=()=>{localStorage.setItem('bc_accounts',JSON.stringify(accounts));localStorage.setItem('bc_requests',JSON.stringify(requests));localStorage.setItem('bc_updates',JSON.stringify(updates))};
function toast(message){const t=$('#toast');if(!t)return;t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function ensureRoleChoice(){const form=$('#signupForm');if(!form||$('#signupRole'))return;const label=document.createElement('label');label.innerHTML='Account type<select id="signupRole"><option value="citizen">Barangay Citizen / User</option><option value="admin">Barangay Admin</option></select>';form.insertBefore(label,form.firstElementChild?.nextElementSibling||form.firstChild)}
function showCitizen(){if(!currentUser||currentUser.role==='admin')return;$('#authView')?.classList.add('hidden');$('#appView')?.classList.remove('hidden');if($('#userName'))$('#userName').textContent=currentUser.name;if($('#welcomeName'))$('#welcomeName').textContent=currentUser.name.split(' ')[0];renderRequests();renderUpdates();updateStats()}
function openPortal(user){localStorage.setItem('bc_user',JSON.stringify(user));if(user.role==='admin'){location.href='admin.html'}else{currentUser=user;showCitizen();toast('Matagumpay na naka-login!')}}
function renderRequests(){const list=$('#requestsList');if(!list||!currentUser)return;const q=($('#searchRequests')?.value||'').toLowerCase(),f=$('#statusFilter')?.value||'all';const rows=requests.filter(r=>(!r.owner||r.owner===currentUser.email||r.owner==='resident')&&(f==='all'||r.status===f)&&`${r.type} ${r.id} ${r.purpose}`.toLowerCase().includes(q));list.innerHTML=rows.length?rows.map(r=>`<article class="request-item"><div><h3>${r.type}</h3><small>${r.id} • ${r.date} • ${r.purpose}</small></div><span class="status ${r.status.toLowerCase().replace(' ','-')}">${r.status}</span></article>`).join(''):'<div class="request-item"><div><h3>Walang nahanap na request</h3><small>Mag-submit ng bagong request para makita dito.</small></div></div>'}
function renderUpdates(){const list=$('#communityUpdates');if(list)list.innerHTML=updates.map((u,i)=>`<article class="update-card ${i===0?'featured':''}"><span class="tag">${u.type}</span><h2>${u.title}</h2><p>${u.details}</p><small>📅 ${u.date}</small></article>`).join('')}
function updateStats(){const own=requests.filter(r=>!r.owner||r.owner===currentUser.email||r.owner==='resident');if($('#pendingCount'))$('#pendingCount').textContent=own.filter(r=>r.status==='Pending').length;if($('#processCount'))$('#processCount').textContent=own.filter(r=>r.status==='In process').length;if($('#completedCount'))$('#completedCount').textContent=own.filter(r=>r.status==='Completed').length}
function goPage(page){$$('.page').forEach(p=>p.classList.add('hidden'));$(`#${page}Page`)?.classList.remove('hidden');$$('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.page===page))}
function bind(){ensureRoleChoice();$$('.auth-tab').forEach(tab=>tab.onclick=()=>{$$('.auth-tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');$('#loginForm')?.classList.toggle('hidden',tab.dataset.auth!=='login');$('#signupForm')?.classList.toggle('hidden',tab.dataset.auth!=='signup');ensureRoleChoice()});$('#loginBtn')?.addEventListener('click',()=>{const email=$('#loginEmail').value.trim().toLowerCase(),password=$('#loginPassword').value,user=accounts.find(a=>a.email===email&&a.password===password);if(!user)return toast('Maling email o password.');openPortal(user)});$('#signupBtn')?.addEventListener('click',()=>{const role=$('#signupRole')?.value||'citizen',name=$('#signupName').value.trim(),email=$('#signupEmail').value.trim().toLowerCase(),password=$('#signupPassword').value,password2=$('#signupPassword2')?.value||password;if(!name||!email||password.length<6||password!==password2||!$('#terms').checked)return toast('Punan nang tama ang lahat ng fields.');if(accounts.some(a=>a.email===email))return toast('May account na gamit ang email na ito. Mag-login na lang.');const user={name,email,password,role};accounts.push(user);save();openPortal(user)});$$('[data-page]').forEach(e=>e.onclick=()=>goPage(e.dataset.page));$('#searchRequests')?.addEventListener('input',renderRequests);$('#statusFilter')?.addEventListener('change',renderRequests);$$('[data-modal]').forEach(e=>e.onclick=()=>$('#requestModal')?.classList.remove('hidden'));$$('.modal-close').forEach(e=>e.onclick=()=>e.closest('.modal')?.classList.add('hidden'));$('#settingsBtn')?.addEventListener('click',()=>$('#settingsModal')?.classList.remove('hidden'));$('#logoutBtn')?.addEventListener('click',()=>{localStorage.removeItem('bc_user');location.reload()});$('#requestForm')?.addEventListener('submit',e=>{e.preventDefault();requests.unshift({id:`REQ-2026-${String(requests.length+1).padStart(3,'0')}`,type:$('#documentType').value,date:new Date().toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'}),status:'Pending',purpose:$('#requestReason').value,owner:currentUser.email});save();e.target.reset();$('#requestModal').classList.add('hidden');renderRequests();updateStats();goPage('requests');toast('Na-submit na ang request!')});$('#passwordForm')?.addEventListener('submit',e=>{e.preventDefault();const a=accounts.find(x=>x.email===currentUser.email);if(a.password!==$('#currentPassword').value)return toast('Mali ang current password.');if($('#newPassword').value.length<6||$('#newPassword').value!==$('#newPassword2').value)return toast('Hindi tugma ang bagong password.');a.password=$('#newPassword').value;currentUser=a;save();localStorage.setItem('bc_user',JSON.stringify(a));e.target.reset();$('#settingsModal').classList.add('hidden');toast('Na-update ang password.')})}
// The admin portal is separate. Remove accidental admin markup if it was copied below index.html.
function removeAccidentalAdmin(){if(location.pathname.endsWith('/index.html')||location.pathname.endsWith('/')){$('#adminLogin')?.remove();$('#adminApp')?.remove()}}
removeAccidentalAdmin();bind();if(currentUser?.role==='admin')location.href='admin.html';else if(currentUser)showCitizen();
