const seedRequests=[{id:'REQ-2026-001',type:'Certificate of Indigency',date:'September 14, 2026',status:'Pending',purpose:'Medical assistance'},{id:'REQ-2026-002',type:'Barangay Certificate',date:'September 08, 2026',status:'In process',purpose:'Job application'},{id:'REQ-2026-003',type:'Barangay Certificate',date:'August 22, 2026',status:'Completed',purpose:'School requirement'},{id:'REQ-2026-004',type:'Business Clearance',date:'July 19, 2026',status:'Completed',purpose:'Business registration'},{id:'REQ-2026-005',type:'Certificate of Indigency',date:'June 11, 2026',status:'Completed',purpose:'Scholarship'}];
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let currentUser=JSON.parse(localStorage.getItem('bc_user')||'null');
let requests=JSON.parse(localStorage.getItem('bc_requests')||'null')||seedRequests;
function save(){localStorage.setItem('bc_requests',JSON.stringify(requests))}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
function showApp(){if(!currentUser)return;$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');const name=currentUser.name||'Juan Dela Cruz';$('#userName').textContent=name;$('#welcomeName').textContent=name.split(' ')[0];renderRequests();updateStats()}
function showAuth(){currentUser=null;localStorage.removeItem('bc_user');$('#appView').classList.add('hidden');$('#authView').classList.remove('hidden')}
function goPage(page){$$('.page').forEach(p=>p.classList.add('hidden'));$(`#${page}Page`).classList.remove('hidden');$$('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.page===page));window.scrollTo({top:0,behavior:'smooth'})}
function renderRequests(){const list=$('#requestsList');if(!list)return;const query=($('#searchRequests')?.value||'').toLowerCase();const filter=$('#statusFilter')?.value||'all';const data=requests.filter(r=>(filter==='all'||r.status===filter)&&(`${r.type} ${r.id} ${r.purpose}`.toLowerCase().includes(query)));list.innerHTML=data.length?data.map(r=>`<article class="request-item"><div><h3>${r.type}</h3><small>${r.id} • ${r.date} • ${r.purpose}</small></div><span class="status ${r.status.toLowerCase().replace(' ','-')}">${r.status}</span></article>`).join(''):'<div class="request-item"><div><h3>Walang nahanap na request</h3><small>Subukan ang ibang search o mag-submit ng bagong request.</small></div></div>'}
function updateStats(){$('#pendingCount').textContent=requests.filter(r=>r.status==='Pending').length;$('#processCount').textContent=requests.filter(r=>r.status==='In process').length;$('#completedCount').textContent=requests.filter(r=>r.status==='Completed').length}
$$('.auth-tab').forEach(tab=>tab.addEventListener('click',()=>{$$('.auth-tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');$('#loginForm').classList.toggle('hidden',tab.dataset.auth!=='login');$('#signupForm').classList.toggle('hidden',tab.dataset.auth!=='signup')}));
$('#loginBtn').addEventListener('click',()=>{const email=$('#loginEmail').value.trim(),pass=$('#loginPassword').value;if(email==='admin@barangay.ph'&&pass==='admin123'){currentUser={name:'Barangay Admin',email};localStorage.setItem('bc_user',JSON.stringify(currentUser));showApp();toast('Matagumpay na naka-login!')}else if(email&&pass.length>=6){currentUser={name:email.split('@')[0],email};localStorage.setItem('bc_user',JSON.stringify(currentUser));showApp();toast('Matagumpay na naka-login!')}else toast('Ilagay ang tamang email at password.')});
$('#signupBtn').addEventListener('click',()=>{const name=$('#signupName').value.trim(),email=$('#signupEmail').value.trim(),pass=$('#signupPassword').value;if(!name||!email||pass.length<6||!$('#terms').checked)return toast('Punan ang lahat ng fields at sumang-ayon sa terms.');currentUser={name,email};localStorage.setItem('bc_user',JSON.stringify(currentUser));showApp();toast('Account created! Maligayang pagdating.')});
$('#logoutBtn').addEventListener('click',showAuth);$('#mobileMenu').addEventListener('click',()=>$('#mainNav').classList.toggle('open'));
$$('[data-page]').forEach(el=>el.addEventListener('click',e=>{if(el.dataset.page){goPage(el.dataset.page);$('#mainNav').classList.remove('open')}}));
$$('[data-modal]').forEach(el=>el.addEventListener('click',()=>$('#requestModal').classList.remove('hidden')));$$('.modal-close').forEach(el=>el.addEventListener('click',()=>$('#requestModal').classList.add('hidden')));
$$('.service-card').forEach(card=>card.addEventListener('click',()=>{$('#documentType').value=card.dataset.request;$('#requestModal').classList.remove('hidden')}));
$('#requestForm').addEventListener('submit',e=>{e.preventDefault();const type=$('#documentType').value;if(!type)return toast('Pumili ng dokumento.');requests.unshift({id:`REQ-2026-${String(requests.length+1).padStart(3,'0')}`,type,date:new Date().toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'}),status:'Pending',purpose:$('#requestReason').value});save();renderRequests();updateStats();$('#requestModal').classList.add('hidden');e.target.reset();goPage('requests');toast('Na-submit na ang iyong request!')});
$('#searchRequests').addEventListener('input',renderRequests);$('#statusFilter').addEventListener('change',renderRequests);$('.close-notice').addEventListener('click',e=>e.target.closest('.notice').remove());$$('.toggle-password').forEach(btn=>btn.addEventListener('click',()=>{const input=btn.previousElementSibling;input.type=input.type==='password'?'text':'password';btn.textContent=input.type==='password'?'Show':'Hide'}));
if(currentUser)showApp();
